version: "2"

run:
  timeout: 3m

linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - errorlint
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused
  settings:
    revive:
      rules:
        - name: exported
        - name: var-naming
          arguments:
            - [] # allowlist
            - [] # blocklist
            - - skip-package-name-checks: true
        - name: package-comments
          disabled: true
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - revive

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/peuf0u/simsquad
