package skills

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"regexp"
	"strconv"
	"strings"
)

// The generated-file header is one line. It tells humans not to edit the
// file and carries what Install and ReadInstalled need: the binary version,
// the skill contract and a checksum of the rest of the file. The checksum
// is what makes hand-edit detection work across binary versions: a file is
// pristine when its body still hashes to the value in its own header,
// whichever simsquad wrote it.
const headerNote = "Do not edit: put project knowledge in qa/README.md and re-run `simsquad skill install` to update."

var headerRe = regexp.MustCompile(`Generated by simsquad (.+?), skill contract (\d+)\. .*sha256:([0-9a-f]{64})`)

// commentStyle wraps the header in the comment syntax of the file's type.
type commentStyle struct{ open, close string }

var (
	htmlComment = commentStyle{"<!-- ", " -->"}
	hashComment = commentStyle{"# ", ""}
)

func styleFor(name string) commentStyle {
	if strings.HasSuffix(name, ".md") {
		return htmlComment
	}
	return hashComment
}

// header holds the fields parsed back from a generated file.
type header struct {
	Version  string
	Contract int
	Sum      string
}

func checksum(body string) string {
	s := sha256.Sum256([]byte(body))
	return hex.EncodeToString(s[:])
}

// stamp inserts the header into body. Markdown with YAML frontmatter keeps
// the frontmatter first (agent tools parse it from the top of the file), so
// the header goes right after it; everything else gets it on line one.
func stamp(name, body, version string) string {
	st := styleFor(name)
	line := fmt.Sprintf("%sGenerated by simsquad %s, skill contract %d. %s sha256:%s%s\n",
		st.open, version, Contract, headerNote, checksum(body), st.close)
	if strings.HasPrefix(body, "---\n") {
		if end := strings.Index(body[4:], "\n---\n"); end >= 0 {
			cut := 4 + end + len("\n---\n")
			return body[:cut] + line + body[cut:]
		}
	}
	return line + body
}

// parse finds the header in content and returns it together with content
// minus the header line. ok is false when no header is present.
func parse(content string) (h header, body string, ok bool) {
	lines := strings.SplitAfter(content, "\n")
	for i, l := range lines {
		m := headerRe.FindStringSubmatch(l)
		if m == nil {
			continue
		}
		n, err := strconv.Atoi(m[2])
		if err != nil {
			return header{}, "", false
		}
		rest := strings.Join(append(append([]string{}, lines[:i]...), lines[i+1:]...), "")
		return header{Version: m[1], Contract: n, Sum: m[3]}, rest, true
	}
	return header{}, "", false
}

// pristine reports whether content is a generated file nobody edited by
// hand since simsquad wrote it.
func pristine(content string) bool {
	h, body, ok := parse(content)
	return ok && checksum(body) == h.Sum
}
