package skills_test

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/peuf0u/simsquad/internal/agenttest"
	"github.com/peuf0u/simsquad/internal/cli"
	"github.com/peuf0u/simsquad/internal/contract"
	"github.com/peuf0u/simsquad/internal/skills"
)

// installedTestSkill installs the skills into a temp repo and returns the
// simsquad-test skill's SKILL.md and worker.md as an agent would read them.
func installedTestSkill(t *testing.T) (skill, worker string) {
	t.Helper()
	root := t.TempDir()
	if _, err := skills.Install(skills.Options{Root: root, Version: "0.4.0"}); err != nil {
		t.Fatal(err)
	}
	dir := filepath.Join(root, skills.DefaultDir, "simsquad-test")
	read := func(name string) string {
		b, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			t.Fatal(err)
		}
		return string(b)
	}
	return read("SKILL.md"), read("worker.md")
}

// fencedCommands returns the command lines inside fenced code blocks that
// start with prog, with backslash continuations joined into one line.
func fencedCommands(doc, prog string) []string {
	var out []string
	inFence := false
	pending := ""
	for _, line := range strings.Split(doc, "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "```") {
			inFence = !inFence
			pending = ""
			continue
		}
		if !inFence {
			continue
		}
		if pending != "" {
			trimmed = pending + " " + trimmed
			pending = ""
		}
		if strings.HasSuffix(trimmed, `\`) {
			pending = strings.TrimSuffix(trimmed, `\`)
			continue
		}
		if strings.HasPrefix(trimmed, prog+" ") {
			out = append(out, trimmed)
		}
	}
	return out
}

func TestTestSkillShipsTheWorkerProcedure(t *testing.T) {
	skill, worker := installedTestSkill(t)
	if !strings.Contains(skill, "worker.md") {
		t.Error("SKILL.md does not point workers at worker.md")
	}
	if !strings.Contains(worker, "Generated by simsquad") {
		t.Error("worker.md lacks the generated-file header")
	}
}

// The procedure calls every step of a test run, in the spec's order.
func TestTestSkillWalksTheTestRunProcedureInOrder(t *testing.T) {
	skill, _ := installedTestSkill(t)
	cmds := strings.Join(fencedCommands(skill, "simsquad"), "\n")
	last := -1
	for _, step := range []string{
		"simsquad skill status",
		"simsquad run new",
		"simsquad deploy --name",
		"simsquad devices --name",
		"simsquad run worker",
		"simsquad run validate",
		"simsquad run report",
		"simsquad dismiss --name",
	} {
		i := strings.Index(cmds, step)
		if i < 0 {
			t.Errorf("procedure has no `%s` example", step)
			continue
		}
		if i < last {
			t.Errorf("`%s` comes before the step it should follow", step)
		}
		last = i
	}
	for _, want := range []string{"--force-build", "--ready", "claude -p", "codex exec", "Source:", "qa/features/", "@explore"} {
		if !strings.Contains(skill, want) {
			t.Errorf("skill does not mention %q", want)
		}
	}
}

// TestTestSkillWorkerCommandCarriesItsPermissions guards the two ways dry run
// 002 saw a Claude worker fail to start: `claude -p` ignores
// .claude/settings.json in a folder nobody has trusted interactively, so the
// worker command must pass every rule itself; and Claude Code can't check a
// `$(…)` substitution before running it, so it asks for approval.
func TestTestSkillWorkerCommandCarriesItsPermissions(t *testing.T) {
	skill, _ := installedTestSkill(t)
	start := strings.Index(skill, "-- claude -p")
	if start < 0 {
		t.Fatal("skill has no `-- claude -p` worker command")
	}
	end := strings.Index(skill[start:], "```")
	if end < 0 {
		t.Fatal("worker command block is not closed")
	}
	cmd := skill[start : start+end]
	for _, rule := range skills.ClaudeAllow {
		if !strings.Contains(cmd, `"`+rule+`"`) {
			t.Errorf("Claude worker command does not pass --allowedTools %q", rule)
		}
	}
	if strings.Contains(skill, "$(") {
		t.Error("skill uses a $(…) command substitution")
	}
}

// redirectRe matches a shell output redirection (`>`, `>>`, `2>`, `&>`).
var redirectRe = regexp.MustCompile(`(?:^|\s)[0-9&]?>`)

// shellLines returns every line inside the doc's ```sh fences.
func shellLines(doc string) []string {
	var out []string
	inSh, inFence := false, false
	for _, line := range strings.Split(doc, "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "```") {
			inFence = !inFence
			inSh = inFence && trimmed == "```sh"
			continue
		}
		if inSh {
			out = append(out, trimmed)
		}
	}
	return out
}

// Claude Code asks for approval on any shell redirection, even of an
// allowed command, so the skills write JSON with --out instead (issue #16).
func TestTestSkillWritesJSONWithOutNotRedirection(t *testing.T) {
	skill, worker := installedTestSkill(t)
	for name, doc := range map[string]string{"SKILL.md": skill, "worker.md": worker} {
		for _, line := range shellLines(doc) {
			if redirectRe.MatchString(line) {
				t.Errorf("%s redirects output: %s", name, line)
			}
		}
	}
	for _, line := range fencedCommands(skill, "simsquad") {
		if !strings.Contains(line, " --out ") {
			t.Errorf("example does not write its JSON with --out: %s", line)
		}
	}
}

// Deleting a file needs approval in Claude Code, so no step asks for one.
func TestTestSkillNeverDeletesFiles(t *testing.T) {
	skill, worker := installedTestSkill(t)
	for name, doc := range map[string]string{"SKILL.md": skill, "worker.md": worker} {
		for _, line := range shellLines(doc) {
			if regexp.MustCompile(`(?:^|[\s;&|])rm\s`).MatchString(line) {
				t.Errorf("%s removes files: %s", name, line)
			}
		}
		if m := regexp.MustCompile(`(?i)\bdelete\s+(the|this|that)\s+(draft|file)`).FindString(doc); m != "" {
			t.Errorf("%s asks to %q", name, m)
		}
	}
}

// A failed deploy goes straight to the report: the build log path is the
// user's to read, not the orchestrator's to debug (issue #16).
func TestTestSkillSendsFailedDeployStraightToReport(t *testing.T) {
	skill, _ := installedTestSkill(t)
	m := regexp.MustCompile(`(?s)## 5\. Deploy\n(.*?)\n## `).FindStringSubmatch(skill)
	if m == nil {
		t.Fatal("skill has no `## 5. Deploy` step")
	}
	for _, want := range []string{"step 9", "builds", "log"} {
		if !strings.Contains(m[1], want) {
			t.Errorf("deploy step does not mention %q", want)
		}
	}
}

// After `simsquad equip` changes the equipment, deploy refuses the project
// squad ("not reusable") until it's dismissed. Dry run 002 hit this the first
// time Android was added; the skill must recover instead of reporting infra.
func TestTestSkillRedeploysWhenEquipmentChanged(t *testing.T) {
	skill, _ := installedTestSkill(t)
	m := regexp.MustCompile(`(?s)## 5\. Deploy\n(.*?)\n## `).FindStringSubmatch(skill)
	if m == nil {
		t.Fatal("skill has no `## 5. Deploy` step")
	}
	for _, want := range []string{"not reusable", `simsquad dismiss --name "$SQUAD"`} {
		if !strings.Contains(m[1], want) {
			t.Errorf("deploy step does not mention %q", want)
		}
	}
}

// Dry run 002's orchestrator appended `echo "exit $?"` to a simsquad call,
// which turned an allowed command into one needing approval.
func TestTestSkillRunsCommandsUnchained(t *testing.T) {
	skill, _ := installedTestSkill(t)
	if !strings.Contains(skill, "nothing chained") {
		t.Error("skill does not tell the agent to run commands unchained")
	}
}

// Every simsquad command and flag the skill or the worker prompt shows must
// exist on the binary, so neither teaches a command simsquad rejects.
func TestTestSkillUsesOnlyRealSimsquadCommandsAndFlags(t *testing.T) {
	skill, worker := installedTestSkill(t)
	flagRe := regexp.MustCompile(`(?:^|\s)--([a-z][a-z-]*)`)
	for _, line := range append(fencedCommands(skill, "simsquad"), fencedCommands(worker, "simsquad")...) {
		// Flags after `--` belong to the wrapped worker command.
		own, _, _ := strings.Cut(line, " -- ")
		fields := strings.Fields(own)[1:]
		var words []string
		for _, f := range fields {
			if strings.HasPrefix(f, "-") {
				break
			}
			words = append(words, f)
		}
		root := cli.NewRootCmd()
		cmd, rest, err := root.Find(words)
		if err != nil || cmd == root || cmd.HasSubCommands() {
			t.Errorf("unknown command in: %s", line)
			continue
		}
		// `run worker` validates its arguments against the `--` split, which
		// only a real parse sets up; every other command is checked here.
		if cmd.Args != nil && !strings.Contains(line, " -- ") {
			if err := cmd.Args(cmd, rest); err != nil {
				t.Errorf("`%s` rejects its arguments %v: %s", cmd.CommandPath(), rest, line)
			}
		}
		for _, f := range flagRe.FindAllStringSubmatch(own, -1) {
			if cmd.Flags().Lookup(f[1]) == nil && cmd.InheritedFlags().Lookup(f[1]) == nil {
				t.Errorf("`%s` has no --%s flag: %s", cmd.CommandPath(), f[1], line)
			}
		}
	}
}

// mobilecliCommands is the mobilecli 1.0.13 surface workers may use, with
// each command's flags, as printed by `mobilecli <command> --help`.
var mobilecliCommands = map[string][]string{
	"dump ui":      {"device", "format", "full"},
	"io tap":       {"device"},
	"io longpress": {"device"},
	"io text":      {"device"},
	"io swipe":     {"device", "duration"},
	"io button":    {"device"},
	"screenshot":   {"device", "output", "format", "quality", "scale", "max-size"},
	"apps launch":  {"device", "activity", "locale"},
}

func TestWorkerDrivesItsOwnDeviceWithRealMobilecliCommands(t *testing.T) {
	_, worker := installedTestSkill(t)
	cmds := fencedCommands(worker, "mobilecli")
	if len(cmds) == 0 {
		t.Fatal("worker prompt has no mobilecli examples")
	}
	seen := map[string]bool{}
	flagRe := regexp.MustCompile(`(?:^|\s)--([a-z][a-z-]*)`)
	for _, line := range cmds {
		fields := strings.Fields(line)
		name := ""
		for k := range mobilecliCommands {
			if strings.HasPrefix(strings.Join(fields[1:], " ")+" ", k+" ") {
				name = k
			}
		}
		if name == "" {
			t.Errorf("not a mobilecli command workers may use: %s", line)
			continue
		}
		seen[name] = true
		if !strings.Contains(line, "--device ") {
			t.Errorf("mobilecli call does not target the worker's own device: %s", line)
		}
		for _, f := range flagRe.FindAllStringSubmatch(line, -1) {
			ok := false
			for _, allowed := range mobilecliCommands[name] {
				ok = ok || allowed == f[1]
			}
			if !ok {
				t.Errorf("`mobilecli %s` has no --%s flag: %s", name, f[1], line)
			}
		}
	}
	for _, want := range []string{"dump ui", "io tap", "io text", "io swipe", "io button", "screenshot", "apps launch"} {
		if !seen[want] {
			t.Errorf("worker prompt shows no `mobilecli %s` example", want)
		}
	}
	if !strings.Contains(worker, "--format text") {
		t.Error("worker prompt does not read the screen with `dump ui --format text`")
	}
}

func TestWorkerResetsBeforeEveryScenarioAndValidatesItself(t *testing.T) {
	_, worker := installedTestSkill(t)
	cmds := strings.Join(fencedCommands(worker, "simsquad"), "\n")
	for _, want := range []string{"simsquad reset --name", "--device", "simsquad run validate"} {
		if !strings.Contains(cmds, want) {
			t.Errorf("worker prompt has no `%s` example", want)
		}
	}
	for _, want := range []string{"result.json", "log.md", "screenshots/", "qa/README.md", "verbatim"} {
		if !strings.Contains(worker, want) {
			t.Errorf("worker prompt does not mention %q", want)
		}
	}
	for _, platform := range []string{"iOS", "Android"} {
		if !regexp.MustCompile(`(?m)^#+ .*` + platform).MatchString(worker) {
			t.Errorf("worker prompt has no %s quirks section", platform)
		}
	}
}

// The skills speak GLOSSARY.md's language: none of its avoided terms, and
// nothing left over from the pilot's mobile-mcp and Python tooling.
func TestTestSkillAvoidsRetiredVocabulary(t *testing.T) {
	skill, worker := installedTestSkill(t)
	retired := regexp.MustCompile(`(?i)\b(mobile-mcp|mobile_[a-z_]+|mcp|python3?|\.py\b|pilot|smoke|sub-?agents?|testers?|test cases?|test plan|feature context|monkey testing|defects?|lease|fleet)\b`)
	for name, doc := range map[string]string{"SKILL.md": skill, "worker.md": worker} {
		for _, m := range retired.FindAllString(doc, -1) {
			t.Errorf("%s uses retired term %q", name, m)
		}
	}
}

// The result.json example in the worker prompt is what workers copy, so it
// must pass `run validate` once its screenshots exist.
func TestWorkerResultExamplePassesValidation(t *testing.T) {
	_, worker := installedTestSkill(t)
	m := regexp.MustCompile("(?s)## result.json\n\n```json\n(.*?)```").FindStringSubmatch(worker)
	if m == nil {
		t.Fatal("worker prompt has no result.json example")
	}
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, contract.ResultFileName), []byte(m[1]), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(dir, "screenshots"), 0o755); err != nil {
		t.Fatal(err)
	}
	for _, shot := range regexp.MustCompile(`screenshots/[a-z0-9-]+\.png`).FindAllString(m[1], -1) {
		if err := os.WriteFile(filepath.Join(dir, shot), []byte("png"), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	if _, errs := agenttest.ValidateWorkerDir(dir); len(errs) > 0 {
		t.Errorf("example result.json is invalid: %v", errs)
	}
}
